oss-review-toolkit/orthw-shell

- orth
Drop listing all template files explicitly in favor of specifying a
templates directory. So, adding or removing template files no more
requires any changes to `orth` in order to make it produce the
respective notice file.
> orth: Further generalize specifying the notice template files

- orth
The public configuration repository now has a 'custom-licenses'
directory [1]. Pass that directory to the reporter command in order to
have the custom license texts in the notice reports.
[1] https://github.com/oss-review-toolkit/ort-config/pull/41
> orth: Make use of the 'custom-licenses'

- orthw
The `jq` tool was used by a `orthw` command that was removed
so we should not require `jq` to be installed on user system.
> orthw: Remove jq from required commands

- orthw
If the value of `ignore_excluded_rule_ids` is an empty string, which is
the default value in the configuration, then the call to `orth` exits
with [1]. So, add quotes to fix that.
[1] Error: Got unexpected extra argument (ort.yml)
> orthw: Fix an issue with the "offending-licenses" command

- orthw
- orthwconfig-template
Checks using ORT's advisor the security advisory providers specified
in the `~/.orthwconfig` file for currently known security vulnerabilities
for found dependencies.
> orthw: Add `check-advisories` command

- orthw
The MD5 checksum of the package curations was properly handled in
`update_evaluation_md5_sum()` but missing in
`check_evaluation_md5_sum()`. So, when recomputing the report after
making a file change in the package curations directory the evaluator
was not re-run. Add the missing check, analog to the one for package
configurations, to fix that problem.
Fixes #19.
> orthw: Fix the broken `check_evaluation_md5_sum()`

- orthw
ORT's evaluator may return the following exit codes:
`0`: The execution was successful and no severe issues have been found.
`1`: The execution failed.
`2`: The execution succeeded and severe issues have been found.
`orthw` uses an MD5 sum file for checking whether the evaluator needs to
be (re-)run, e.g. inputs have changed. So, don't update the MD5 sums in
case the evaluation fails to ensure the evaluator is run in the next
attempt to generate a report.
Fixes #15.
> orthw: Gracfully handle the exit code of the evalutor

- orthw
- orthwconfig-template
This e.g. enables setting the log level from the configuration.
Note: User's must align their configuration file with these changes.
> Allow for configuring CLI options for `ort` and `orth`

- orthw
Previously, only `.json` and `.json.xz` was supported.
Fixes #32.
Note: Must be **merged only after** https://github.com/oss-review-toolkit/ort/pull/5635.
> Allow initializing with ORT files in `.yml` and `.yml.xz` format

- orthw
In case the users hasn't setup a configuration file the script fails
with a non-informative error message [1]. Output an error message which
indicates what whent wrong and how to fix it.
Fixes https://github.com/oss-review-toolkit/orthw/issues/28.
[1] The variable 'configuration_home' must be defined in [...]
> orthw: Gracefully handle missing configuration file

- orthw
Modify an existing command to generate path excludes and add a new command for the bulk creation of package configurations for all (offending) packages.
Must be merged after https://github.com/oss-review-toolkit/ort/pull/5699.
> orthw: Enable path exclude generation for package configurations

- orthw
This was a work-around to fix name resolution when the host machine is
connected via VPN. On my machine (Ubuntu 22.04) this breaks name
resolution when not connected to VPN. So, drop the mount command to fix
that.
> orthw: Stop mounting `resolve.conf` into docker

- orthw
Both `orthw cyclone-dx` and `orthw spdx` did not produce files anymore
after a rename in ORT[1].
[1]: https://github.com/oss-review-toolkit/ort/commit/0afda77f3180d40ac68705e76f54d1df7145e4ae
> orthw: Fix-up SBOM generation

- orthwconfig-template
See https://github.com/oss-review-toolkit/ort/pull/5812.
While at it, improve the comment to explain setting the log level separately from enabling stack traces.
> orthwconfig-template: Reflect the new log level options in ORT's CLI

- orthw
- orthwconfig-template
The path exclude generation optionally does not generate excludes for files and directories which only have non-offending license findings, see also [1].
Make use of that from `orthw` and add a corresponding configuration option to the configuration file.
[1] https://github.com/oss-review-toolkit/ort/pull/5854
Note: **Must be merged after** https://github.com/oss-review-toolkit/ort/pull/5854.
Part of https://github.com/oss-review-toolkit/ort/issues/5763.
> orthw: Make the path exclude generation configurable

- orthw
The custom license texts directory has been renamed, see [1].
[1] https://github.com/oss-review-toolkit/ort-config/pull/68
> orthw: Re-align a directory name with `ort-config`

- orthw
- orthwconfig-template
This allows skipping the generation of excludes for arbitrary license IDs or for NOASSERTION.
Note: must be merged after https://github.com/oss-review-toolkit/ort/pull/5995.
> orthw: Extend the configuration for the path exclude generation

- docs/getting-started.md
See individual commits for details.
> getting-started.md: Fix missing branch in orthw init URL

- orthw
`bash` may not always be located at `/bin/bash`. Use the one on $PATH instead.
This change makes it possible to use the script on macOS where `/bin/bash` is stuck to version 3.2.57, in which `readarray` is not available. By using `bash` from $PATH a newer version which was installed manually can be used.
> orthw: Change Shebang to use bash from $PATH

- orthw
Re-align with the changed property paths, see [1].
Fixes #57.
[1] https://github.com/oss-review-toolkit/ort/commit/4ea98636ff2e510bafc9fd8300433ed0cf204304
> orthw: Fix-up passing the postgres storage configuration

- orthw
See https://github.com/oss-review-toolkit/ort/pull/6858.
> refactor(orthw)!: Align with the renamed `--package-configuration-dir`

- orthw
Ensure that the storage only contains the files corresponding to the ORT file the directory is (re-)initialized with.
> chore(orthw): Also delete the scan storage dir during init

- orthw
As of [1][2], one has to provide `--refresh-resolutions` in order to make ORT consume the resolutions provided via `--resolutions-file`. If that flag is absent, ORT ignores the provided resolution in case the resolved configuration within the ORT file already contains resolutions.
So, provide that flag to ensure the resolutions get applied in the reporter stage.
[1] https://github.com/oss-review-toolkit/ort/commit/80605dc20495756c72df03179dcce6b5fba8d5ca
[2] https://github.com/oss-review-toolkit/ort/commit/ab99cdc8853a128df05207b88afbd2b76588f111
> fix(orthw): Re-apply the resolutions in the reporter stage

- README.md
`md5sum` is part of `coreutils`.
Fixes #62.
> docs(README): Fix installation instruction for `md5sum` on Ubuntu

- orthw
The option has been removed from ORT's CLI without any replacement. The only way to pass curations is via the `config.yml`.
Fixes #64.
> fix(orthw): Drop the `--package-curations-dir` option

- orthw
Some package managers use `git` for the dependency resolutions such as the SwiftPM. So, mount the hosts `.ssh` dir so that the package managers can properly authenticate against `git` repositories.
> orthw: Mount the `$HOME/.ssh/` when running docker

- README.md
Using the `PATH` instructions could lead to a reader still using non-Bash terminal resulting in unclear error messages. Whereas using an `alias` we can set the terminal to be used explicitly.
> docs(README): Replace path instructions with alias

- orthw
Default format was changed in ORT from XML to JSON [1].
[1]: ...
> fix(orthw): Change format of CycloneDX report

- orthw
Fix up for exxa73b [1] which resulted in the cyclone-dx-report.json to be overwritten with the XML format.
[1]: https://github.com/oss-review-toolkit/orthw-shell/commit/ecca73b708f3b7b0f2bad363816b7b47620654ef
> fix(orthw): Fix up generation of CycloneDX JSON
